// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thezceodkcmkrjprtcjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoZXpjZW9ka2Nta3JqcHJ0Y2pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTc1NjMsImV4cCI6MjA2MjUzMzU2M30.M_BRXeGhrn9-pHVJlA3Rd5H00zfCtACYr76QwAJs2qM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);